package io.github.jho951.assignment.job.domain

enum class JobFailureCode {
    MISSING_IDEMPOTENCY_KEY,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_REQUEST,
    IDEMPOTENCY_KEY_CONFLICT,
    JOB_NOT_FOUND,
    RESULT_NOT_READY,
    WORKER_TIMEOUT,
    WORKER_UNAVAILABLE,
    WORKER_AUTH_FAILED,
    WORKER_BAD_REQUEST,
    MAX_ATTEMPTS_EXCEEDED,
    INTERNAL_ERROR
}
