package io.github.jho951.assignment.order.domain;

public enum JobFailureCode {
    MISSING_IDEMPOTENCY_KEY,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_REQUEST,
    IDEMPOTENCY_KEY_CONFLICT,
    JOB_NOT_FOUND,
    RESULT_NOT_READY,
    BROKERAGE_TIMEOUT,
    BROKERAGE_UNAVAILABLE,
    BROKERAGE_AUTH_FAILED,
    BROKERAGE_BAD_REQUEST,
    BROKERAGE_ORDER_REJECTED,
    BROKERAGE_ORDER_CANCELLED,
    MAX_ATTEMPTS_EXCEEDED,
    INTERNAL_ERROR
}
